runtime: nodejs22

handlers:
  - url: /.*
    script: auto

env_variables:
  DATABASE_URL: "postgresql://neondb_owner:npg_uSqdFMEL7eX1@ep-noisy-credit-a8eab2hc-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"
  NODE_ENV: production

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10  # You can set this value as per your needs
